#!/bin/bash
if [[ $# -eq 0 ]]; then
    echo "Usage : $0 [kernel] [out]"
    exit 1
fi
echo -ne "Symbols:\n$(nm $1)\n" > $2
echo -ne "Sections size:\n$(size $1)\n" >> $2
echo -ne "Kernel size: $(du -sh $1 | awk '{print $1}')\n" >> $2
echo -ne "Readelf:\n $(readelf -a $1)\n" >> $2
echo -ne "Object dump(WARN: LARGE OUTPUT):\n $(objdump -d $1)\n" >> $2
echo -ne "Object dump(.data section):\n $(objdump -s -j .data $1)\n" >> $2
